In [0]:
import numpy as np

#Code perceptron from scratch, gates and early stopping implemented


In [0]:
class binaryPerceptron:

  def __init__(self, wts, th, alpha, tolerance = 1, patience = 5):
    self.weights = np.asarray(wts).reshape(len(wts),1)
    self.feature_length = len(self.weights)
    self.th = th
    self.learning_rate = alpha
    self.tolerance = tolerance
    self.patience = patience
  
  def activation(self, x):
    return 1 if x > self.th else 0

  def predict_single(self, x):
    return self.activation(x.dot(self.weights).sum())

  def predict(self, x):
    y = np.zeros(len(x))
    for i, item in enumerate(x):
      y[i] = self.predict_single(item)
    return y

  def fit(self, x, y, iterations = 100):
    e = 0
    k = 0
    for i in range(iterations):
      t = self.learn_epoch(x,y)
      if abs(t-e) < self.tolerance:
        k += 1
      else:
        k = 0
      if k >= self.patience:
        print('Model has reached its capacity')

  def learn_epoch(self, x, y):
    e = 0
    for feature, target in zip(x,y):
      e += abs(self.learn_single(feature, target))
    return e

  def learn_single(self, x, y):
    e = self.loss_func(y, self.predict_single(x))
    dw = self.learning_rate * e * x.reshape(self.feature_length, 1)
    self.weights += dw
    return e

  def loss_func(self, t, o):
    return t - o

##Parameters

In [0]:
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_AND = np.array([0, 0, 0, 1])
y_OR = np.array([0, 1, 1, 1])
y_XOR = np.array([0, 1, 1, 0])
w = np.array([0.3, -0.1])
th =  0.2
learning_rate = 0.1

##AND Gate

In [0]:
p = binaryPerceptron(w, th, learning_rate)
for i in range(10):
  print(p.learn_epoch(x,y_AND))
p.predict(x)

2
2
1
0
0
0
0
0
0
0


array([0., 0., 0., 1.])

##OR Gate

In [0]:
p = binaryPerceptron(w, th, learning_rate)
for i in range(10):
  print(p.learn_epoch(x,y_OR))
p.predict(x)

2
1
0
0
0
0
0
0
0
0


array([0., 1., 1., 1.])

##XOR Gate (Does not seem like it can be realised by a single perceptron)

In [0]:
p = binaryPerceptron(w, th, learning_rate)
p.fit(x, y_XOR, iterations = 10)
print(p.predict(x))
print(p.weights)

[0. 0. 0. 1.]
[[0.2]
 [0.1]]
